//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int ID { get; set; }
        public string IPSERVIDOR { get; set; }
        public string IPCONTROLGAS1 { get; set; }
        public string IPCONTROLGAS2 { get; set; }
        public string IPPLC { get; set; }
        public string REPORTESPOR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
