//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSGlobal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GLOBAL_BMW1 : DbContext
    {
        public GLOBAL_BMW1()
            : base("name=GLOBAL_BMW1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Areas { get; set; }
        public DbSet<Compania> Companias { get; set; }
        public DbSet<Config_correos> Config_correos { get; set; }
        public DbSet<Configuracion> Configuracions { get; set; }
        public DbSet<Departamento> Departamentos { get; set; }
        public DbSet<Edificio> Edificios { get; set; }
        public DbSet<Logger> Loggers { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Modulo> Modulos { get; set; }
        public DbSet<Perfil_Edificios> Perfil_Edificios { get; set; }
        public DbSet<Perfil_Modulos> Perfil_Modulos { get; set; }
        public DbSet<Perfil_Sistemas> Perfil_Sistemas { get; set; }
        public DbSet<PerfilesUsuario> PerfilesUsuarios { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SessionLog> SessionLogs { get; set; }
        public DbSet<Sistema> Sistemas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<GetAllLogger> GetAllLoggers { get; set; }
        public DbSet<GetAllPerfil_Edificios> GetAllPerfil_Edificios { get; set; }
        public DbSet<GetAllPerfil_Modulos> GetAllPerfil_Modulos { get; set; }
        public DbSet<GetAllPerfil_Sistemas> GetAllPerfil_Sistemas { get; set; }
        public DbSet<GetUserDataTag> GetUserDataTags { get; set; }
        public DbSet<GetUsersTag> GetUsersTags { get; set; }
        public DbSet<viewLogger> viewLoggers { get; set; }
        public DbSet<viewRole> viewRoles { get; set; }
        public DbSet<viewSesionLog> viewSesionLogs { get; set; }
        public DbSet<viewSystem> viewSystems { get; set; }
    }
}
