//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewLogger
    {
        public int id { get; set; }
        public string TextoLog { get; set; }
        public string TagUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string App { get; set; }
        public Nullable<int> IdApp { get; set; }
        public Nullable<int> IdBuilding { get; set; }
        public Nullable<int> IdSystem { get; set; }
        public Nullable<int> IdEquipment { get; set; }
        public string Nombre { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
        public string UserName { get; set; }
        public string Compania { get; set; }
        public string Rol { get; set; }
        public string Telefono { get; set; }
        public string Departamento { get; set; }
        public string Area { get; set; }
        public string Perfil { get; set; }
        public string Sistema { get; set; }
        public string Edificio { get; set; }
        public string Modulo { get; set; }
    }
}
