//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewSesionLog
    {
        public int id { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Logg { get; set; }
        public Nullable<int> IdApp { get; set; }
        public string App { get; set; }
        public string Nombre { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
        public string UserName { get; set; }
        public string Compania { get; set; }
        public string Departamento { get; set; }
        public string Area { get; set; }
        public string Perfil { get; set; }
        public string Telefono { get; set; }
        public string Manager { get; set; }
        public string Modulo { get; set; }
    }
}
